sylius_grid:
    grids:
        setono_sylius_abandoned_cart_admin_unsubscribed_customer:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_abandoned_cart.model.unsubscribed_customer.class%"
            limits: [100, 250, 500, 1000]
            fields:
                email:
                    type: string
                    label: sylius.ui.customer
                createdAt:
                    type: datetime
                    label: sylius.ui.created_at
                    sortable: ~
                    options:
                        format: d-m-Y H:i
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
