sylius_grid:
    grids:
        setono_sylius_abandoned_cart_admin_notification:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_abandoned_cart.model.notification.class%"
            limits: [100, 250, 500, 1000]
            fields:
                order:
                    type: twig
                    label: sylius.ui.order
                    path: cart
                    options:
                        template: "@SetonoSyliusAbandonedCartPlugin/admin/grid/label/cart.html.twig"
                channel:
                    type: twig
                    label: sylius.ui.channel
                    path: cart.channel
                    options:
                        template: "@SyliusAdmin/Order/Grid/Field/channel.html.twig"
                email:
                    type: string
                    label: sylius.ui.customer
                state:
                    type: twig
                    label: setono_sylius_abandoned_cart.ui.state
                    path: .
                    options:
                        template: "@SetonoSyliusAbandonedCartPlugin/admin/grid/label/notification_state.html.twig"
                sentAt:
                    type: datetime
                    label: setono_sylius_abandoned_cart.ui.sent_at
                    sortable: ~
                    options:
                        format: d-m-Y H:i
            actions:
                main:
                    unsubscribed_customers:
                        type: unsubscribed_customers
