setono_sylius_abandoned_cart_admin_notification:
    resource: |
        alias: setono_sylius_abandoned_cart.notification
        section: admin
        permission: true
        templates: '@SyliusAdmin\\Crud'
        redirect: index
        grid: setono_sylius_abandoned_cart_admin_notification
        vars:
            index:
                icon: 'envelope outline'
    type: sylius.resource
