imports:
    - { resource: "@SetonoSyliusAbandonedCartPlugin/Resources/config/grids/setono_sylius_abandoned_cart_admin_notification.yaml" }
    - { resource: "@SetonoSyliusAbandonedCartPlugin/Resources/config/grids/setono_sylius_abandoned_cart_admin_unsubscribed_customer.yaml" }

framework:
    messenger:
        buses:
            setono_sylius_abandoned_cart.command_bus: ~

sylius_grid:
    templates:
        action:
            unsubscribed_customers: "@SetonoSyliusAbandonedCartPlugin/admin/grid/action/unsubscribed_customers.html.twig"

sylius_mailer:
    emails:
        abandoned_cart_email:
            template: "@SetonoSyliusAbandonedCartPlugin/email/notification.html.twig"

sylius_ui:
    events:
        setono_sylius_abandoned_cart.admin.notification.index.javascripts:
            blocks:
                javascript_popup:
                    template: "@SetonoSyliusAbandonedCartPlugin/admin/block/_javascript_popup.html.twig"
