imports:
    - { resource: "@SetonoSyliusAbandonedCartPlugin/Resources/config/grids/setono_sylius_abandoned_cart_admin_notification.yaml" }

framework:
    messenger:
        buses:
            setono_sylius_abandoned_cart.command_bus: ~

sylius_mailer:
    emails:
        abandoned_cart_email:
            template: "@SetonoSyliusAbandonedCartPlugin/email/notification.html.twig"

sylius_ui:
    events:
        setono_sylius_abandoned_cart.admin.notification.index.javascripts:
            blocks:
                javascript_popup:
                    template: "@SetonoSyliusAbandonedCartPlugin/admin/block/_javascript_popup.html.twig"
